[versions]
download = "5.6.0"
junit = "5.10.2"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
download = { id = "de.undercouch.download", version.ref = "download" }
